version: '3'

services:
  web:
    build:
      context: ..
      dockerfile: compose/Dockerfile
    command: python /app/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/compose/app
    ports:
      - '8000:8000'
    depends_on:
      - db
    network_mode: "host"
  db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
      - "POSTGRES_USER=library_admin"
      - "POSTGRES_PASSWORD=library123"
      - "POSTGRES_DB=library_db"
    ports:
      - "5432:5432"
    network_mode: "host"

volumes:
  postgres_data: