version: '3'

services:
  db:
    image: postgres:latest
    container_name: postgres_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
      - "POSTGRES_USER=library_admin"
      - "POSTGRES_PASSWORD=library123"
      - "POSTGRES_DB=library_db"
    ports:
      - "5432:5432"

volumes:
  postgres_data: